Bg grad
euqueme/apple-page pull request #1
Opened 2019-09-02 22:36 UTC by euqueme

2019-09-03 20:02 UTC, uche-inyama reviewed
## Pull request under review by Inyama, Uchechukwu Henry

2019-09-03 20:09 UTC, uche-inyama requested changes
##  Hi Maru! great job :smile:
### Just few changes and you are good.

- [x] There is a validation error, with your Html, correct this.
- [x] Please fix the positioning of your images. I took a snap shot :point_down: 

![Screenshot from 2019-09-03 20-55-16](https://user-images.githubusercontent.com/46329537/64204939-b3e02580-ce8e-11e9-97c4-b9f2f3d2e0bd.png)

### Implement these changes and submit another form for a code review :smiley: 

#### cheers Henry!

2019-09-04 20:10 UTC, samgaco requested changes
#### Hi @euqueme :high_brightness: 

#### Everything is looking good and you went through the requested changes indicated by the previous TSE. Hence the project is approved :+1: Congratulations :100: 

---------

* **[For your next code review requests]**  Use meaningful names for your Pull Requests
* **[For your next code review requests]**  Add a short summary of changes in Pull Request description


* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-04 20:10 UTC, samgaco commented on index.html
> +    </section>
[SUGGESTION] Maybe the `<aside>` tag would fit better this part of the project.

> The <aside> element is used to identify content that is related to the primary content of the webpage, but does not constitute the primary content of the page. Author information, related links, related content, and advertisements are exampes of content that may be found in an aside element.


[Read more](https://html.com/tags/aside/#ixzz5yaXtnPH6)

2019-09-05 22:24 UTC, merged